// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tour_and_travel.data;

#nullable disable

namespace tour_and_travel.Migrations
{
    [DbContext(typeof(addDbContext))]
    partial class addDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tour_and_travel.Models.book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("cadult")
                        .HasColumnType("int");

                    b.Property<int>("cbill")
                        .HasColumnType("int");

                    b.Property<int>("cchild")
                        .HasColumnType("int");

                    b.Property<string>("cdestination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cstay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tour");
                });
#pragma warning restore 612, 618
        }
    }
}
